# Generated by Django 4.0.3 on 2022-03-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_owner'),
        ('answers', '0004_answer_owner_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_owned', to='questions.question'),
        ),
    ]
