# Generated by Django 4.0.3 on 2022-03-03 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_user_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes_recieved',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_sent',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
