# Generated by Django 4.0.3 on 2022-03-03 10:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_alter_user_likes_recieved_alter_user_likes_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes_recieved',
        ),
        migrations.AlterField(
            model_name='user',
            name='likes_sent',
            field=models.ManyToManyField(blank=True, related_name='likes_recieved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pictures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
