# Generated by Django 4.0.3 on 2022-03-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_alter_answer_question'),
        ('jwt_auth', '0008_alter_user_gender_alter_user_interested_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answers_picked',
            field=models.ManyToManyField(blank=True, default=list, to='answers.answer'),
        ),
    ]
