# Generated by Django 4.0.3 on 2022-03-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0009_user_answers_picked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='answers_picked',
            new_name='answers',
        ),
    ]
